setwd("~/Github/2020-Postech-Open-innovation-Bigdata-Challenge")


# import daily weather data
importWeather <- function(){
  data_t_n<-read.csv(file="daily_temperatures_national.csv",stringsAsFactors=FALSE)
  data_t_p<-read.csv(file="daily_temperatures_pohang.csv",stringsAsFactors=FALSE)
  data_t_s<-read.csv(file="daily_temperatures_seoul.csv",stringsAsFactors=FALSE)
  
  data_p_n<-read.csv(file="daily_precipitation_national.csv",stringsAsFactors=FALSE)
  data_p_p<-read.csv(file="daily_precipitation_pohang.csv",stringsAsFactors=FALSE)
  data_p_s<-read.csv(file="daily_precipitation_seoul.csv",stringsAsFactors=FALSE)
  
  data_t<-rbind(data_t_n, data_t_p, data_t_s)
  data_p<-rbind(data_p_n, data_p_p, data_p_s)
  data_p[is.na(data_p)] <- 0
  
  data <- merge(data_t, data_p, by=c("날짜","지점"))
  data["날짜"]<-sapply(data["날짜"], function(x) strptime(x,format="%Y-%m-%d"))
  return(data)
}

# import electrical energy(generated by Solar PV) data (unit : kWh)
importEnergy <- function(){
  data <- read.csv(file="SolarPV_Elec_Problem.csv",header=F,stringsAsFactors=FALSE)
  names(data) <- c("datetime","amount")
  data["datetime"]<-sapply(data["datetime"], function(x) strptime(x,format="%Y-%m-%dT%H:%M:%S+09:00"))
  return(data)
}


weather <- importWeather()
energy <- importEnergy()
